Adding support for graphQL APIs in python
WebFuzzing/EvoMaster pull request #1027
Opened 2024-07-03 18:06 UTC by Pgarrett

This PR adds support for GraphQL APIs, adding the content type header and sending the body in the query

2024-07-03 18:06 UTC, Pgarrett commented
@arcuri82 I believe this is it for python test outputs. Or do you feel something is still missing?

2024-07-03 18:53 UTC, arcuri82 requested changes

2024-07-03 18:53 UTC, arcuri82 commented on core/src/main/kotlin/org/evomaster/core/output/service/GraphQLTestCaseWriter.kt
> +        if (format.isPython()) {
isn't this the same code as done in `RestTestCaseWriter`? if so, should be refactored in a protected utility method, moved up in the hierarchy, eg in `HttpWsTestCaseWriter`

2024-07-03 18:54 UTC, arcuri82 commented
hi @Pgarrett . possibly done, for now. we ll see once we add new set of E2E for black-box, if we get any issue there. thx

2024-07-04 09:44 UTC, arcuri82 approved these changes

2024-07-04 09:44 UTC, merged