Change validations to check shouldGenerateSqlData instead of only search
WebFuzzing/EvoMaster pull request #1077
Opened 2024-09-16 21:45 UTC by agusaldasoro

2024-09-19 07:15 UTC, arcuri82 requested changes

2024-09-20 14:04 UTC, jgaleotti commented on core/src/main/kotlin/org/evomaster/core/problem/api/service/ApiWsStructureMutator.kt
> +        }
what should be the expected behaviour when both are enabled? For example, should it be a 50% probability of picking one of them?

2024-09-20 14:06 UTC, jgaleotti approved these changes

2024-09-23 07:20 UTC, arcuri82 approved these changes

2024-09-23 07:22 UTC, arcuri82 commented
@agusaldasoro @jgaleotti  once CI has passed, we can merge this PR. 
however, we will need to discuss how/if we want to combine SBST/DSE configurations. we can do that by email, or in a meeting

2024-09-24 11:13 UTC, merged